#!/usr/bin/env python3
"""
Total Equines — Excel to horses.js converter
Reads Total_Equines_Pedigree.xlsx and generates a horses.js patch
with updated name + pedigree for each horse found in the Excel.

Usage:
  python excel_to_horses.py
  
Output:
  pedigree_patch.js — paste-ready JS object to update horses.js
"""

import openpyxl
import json
import re

EXCEL_PATH = "Total_Equines_Pedigree.xlsx"

def to_slug(name):
    name = name.lower().strip()
    name = re.sub(r'[áàä]', 'a', name)
    name = re.sub(r'[éèë]', 'e', name)
    name = re.sub(r'[íìï]', 'i', name)
    name = re.sub(r'[óòö]', 'o', name)
    name = re.sub(r'[úùü]', 'u', name)
    name = re.sub(r'[ñ]', 'n', name)
    name = re.sub(r'[^a-z0-9\s-]', '', name)
    name = re.sub(r'\s+', '-', name.strip())
    return name

def title_case(s):
    return ' '.join(w.capitalize() for w in s.strip().split())

wb = openpyxl.load_workbook(EXCEL_PATH)
ws = wb.active

# Skip header rows (1=title, 2=subtitle, 3=column headers)
horses = []
for row in ws.iter_rows(min_row=4, values_only=True):
    name = row[0]
    if not name or str(name).strip() == '':
        continue

    def clean(val):
        if val is None: return ''
        v = str(val).strip()
        return '' if v == '—' else v

    h = {
        "name": title_case(clean(name)),
        "slug": to_slug(clean(name)),
        "pedigree": {
            "sire":     {"name": title_case(clean(row[1])), "origin": clean(row[2])},
            "sireSire": {"name": title_case(clean(row[3])), "origin": clean(row[4])},
            "sireDam":  {"name": title_case(clean(row[5])), "origin": clean(row[6])},
            "dam":      {"name": title_case(clean(row[7])), "origin": clean(row[8])},
            "damSire":  {"name": title_case(clean(row[9])), "origin": clean(row[10])},
            "damDam":   {"name": title_case(clean(row[11])), "origin": "ARG"},
        }
    }
    horses.append(h)

# Generate JS output
lines = []
lines.append("// ─────────────────────────────────────────────────────────────")
lines.append("// AUTO-GENERATED by excel_to_horses.py — Total Equines Pedigree")
lines.append("// Paste each block into the matching horse object in horses.js")
lines.append("// Match by: id (slug) or name")
lines.append("// ─────────────────────────────────────────────────────────────")
lines.append("")
lines.append("export const pedigreePatches = [")

for h in horses:
    p = h["pedigree"]
    lines.append(f"  {{")
    lines.append(f"    // ── {h['name']} ──")
    lines.append(f"    id: '{h['slug']}',")
    lines.append(f"    name: '{h['name']}',")
    lines.append(f"    pedigree: {{")
    lines.append(f"      sire:     {{ name: '{p['sire']['name']}',     origin: '{p['sire']['origin']}' }},")
    lines.append(f"      dam:      {{ name: '{p['dam']['name']}',      origin: '{p['dam']['origin']}' }},")
    lines.append(f"      sireSire: {{ name: '{p['sireSire']['name']}', origin: '{p['sireSire']['origin']}' }},")
    lines.append(f"      sireDam:  {{ name: '{p['sireDam']['name']}',  origin: '{p['sireDam']['origin']}' }},")
    lines.append(f"      damSire:  {{ name: '{p['damSire']['name']}',  origin: '{p['damSire']['origin']}' }},")
    lines.append(f"      damDam:   {{ name: '{p['damDam']['name']}',   origin: '{p['damDam']['origin']}' }},")
    lines.append(f"    }},")
    lines.append(f"  }},")
    lines.append("")

lines.append("];")
lines.append("")
lines.append("// ─── APPLY PATCHES TO horses.js ───────────────────────────────")
lines.append("// Add this helper at the bottom of horses.js and call applyPatches():")
lines.append("//")
lines.append("// import { pedigreePatches } from './pedigreePatches.js';")
lines.append("//")
lines.append("// export function applyPatches(horseArray, patches) {")
lines.append("//   return horseArray.map(horse => {")
lines.append("//     const patch = patches.find(")
lines.append("//       p => p.name.toLowerCase() === horse.name.toLowerCase()")
lines.append("//     );")
lines.append("//     return patch ? { ...horse, ...patch } : horse;")
lines.append("//   });")
lines.append("// }")

output = "\n".join(lines)

with open("pedigreePatches.js", "w", encoding="utf-8") as f:
    f.write(output)

print(f"✓ Generated {len(horses)} horse patches")
print("✓ Output: pedigreePatches.js")
